logging:
  level: INFO
  loggers:
    net.spinetrak.enpassant: DEBUG

dsbData:
  url: https://dwz.svw.info/services/files/export/csv/LV-0-csv.zip
  refreshInterval: 86400

server:
  rootPath: /api/
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: ${PORT:-7777}

database:
  driverClass: org.postgresql.Driver
  user: enpassant
  password: enpassant
  url: jdbc:postgresql://localhost/enpassant
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
